# Generated by Django 4.2.3 on 2023-08-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='seraj', max_length=100),
            preserve_default=False,
        ),
    ]
